# Имя сервиса (обязательно для Eureka)
spring.application.name=user-service

# Подключение к Config Server (внешние настройки)
spring.config.import=optional:configserver:http://localhost:8888

# Eureka (регистрация в Discovery Server)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Порт (меняем, чтобы не конфликтовать с Gateway)
server.port=8082